spring.application.name=ms-auth

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate

# Security login
spring.security.user.name=admin
spring.security.user.password=admin